sudo: required

env:
  global:
    - PROJECT_NAME=multipl
    - DOCKER_IMAGE_NAME=cast-publish
    - GO111MODULE=on

language: go
go:
  - "1.12"

# Cache Gcloud SDK between commands
cache:
  directories:
    - "$HOME/google-cloud-sdk/"

services:
  - docker

before_script:
  - env GO111MODULE=on make test

script:
  - env GO111MODULE=on make image

before_deploy:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash >/dev/null; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update
  - git clone https://github.com/multiplio/MANAGE
  - ./MANAGE/gcloud/auth.sh

deploy:
  - provider: script
    script: ./MANAGE/gcloud/push.sh
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: ./MANAGE/gcloud/push-tag.sh
    skip_cleanup: true
    on:
      tags: true

notifications:
  slack:
    secure: "VhWB3DPJhEolU3ytSisXt6TGWYa1Ba3NfR5qnVQ+D3hfHXA9KtZKnjQaNSyfHFhqj2mesGXNB/4t7EfhSWze1tInjK2eFHsYeajGb5maOSSPcFEJ1MCBO93gHmAGHWViRHeVTnlXFBBXArJYAk/Y+vOcs+7nhlRT/ND1Y54EqP0hi/+W2iMPEMN9nHNsxRfOB3mHMRQMirwP23WRp2bpI36tMUt2LaMA5OKEMF+gJ6noNeiFQ7A4Y38T1kLH6uGShy3Tlm2LmdGsYXOTSo2LlPJstRVI9hGRjOCUR7LD6dNQ8pNhHILZTZstiXLezSxndxAKwTSOXzSYlg2cKTuMw+uFZjo1hFbMkbvbq+73lYDwo5AUIq+MA37PhxDUVFaqOfRQ90sTB6RY/HzfItWrQJ/9chUcsbqyQz1nQWkuNMQQuOBnRZp20qzj4jm5C9WsX3J8sTkj+PQ1Np86iEmU66mlZVKwnDNSjLINfzv1gHRRLCHisonlusCQMm2X1TiF72jhjivoA9UOrYtGjThtGQI8ZCxJhpDqrztxPvaCU6hYXGG+qRPxDoLc86a6NYOQYFs5jJvD5okYr+DrgXAaVDTBb63JXvZ4HrZN0Xj3il0b6KpMdSEjLwQDs7O3g83+ihJc+6pMRB2fk9rlpwuciYpxTPqkyTwOGbg9cHZ3R1I="
